import azure.functions as func
import logging
import json
import os
from openai import AzureOpenAI

# Azure OpenAI をコールするためのインスタンス (今回使用するモデルは gpt-4o)
client = AzureOpenAI(
    api_key=os.environ["OPENAI_KEY"],  
    api_version="2024-07-01-preview",
    azure_endpoint=os.environ["OPENAI_ENDPOINT"]
)

# システムプロンプト
SYSTEM_PROMPT = """
あなたはトリオ漫才のつっこみ役です。あなたと会話している人が次の2点を教えてくれます。
# 受け取るフォーマット
[A] 説明したシチュエーションと話題の情報 (話のフリ役)
[B] Aさんのコメントを受けて解答したコメント (ボケ役)
Bさんは必ずコメントでボケてきますので、あなたはそれに対して勢いがあるwitかつ強めなブラックジョークに富んだツッコミをしてください。
# サンプル 
受け取るテキスト
[A] やぁ、B君Cさん。明日から夏休みだね。私はプール行ったり海に行ったり忙しくなりそうだよ。B君はどう？
[B] 僕は雪だるま作ったりスノボしたりで忙しくなりそうだよ。
※ あなたが生成するテキスト 
雪なんかあるかい！
"""

# Azure OpenAI の Chat Completions API をコールする関数
def chat_completions(req_text: str) -> str:
    """
    Calls the Azure OpenAI Chat Completions API with the given text and system prompt.

    Args:
        req_text (str): The input text to send to the API.

    Returns:
        str: The response text generated by the API.
    """
    response = client.chat.completions.create(
        model="gpt-4o",
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": req_text}
        ]
    )
    return response.choices[0].message.content  

app = func.FunctionApp(http_auth_level=func.AuthLevel.ANONYMOUS)

@app.route(route="http_trigger")  
def http_trigger(req: func.HttpRequest) -> func.HttpResponse: 
    """
    HTTP trigger function to process a request and return a response from Azure OpenAI.

    Args:
        req (func.HttpRequest): The HTTP request object.

    Returns:
        func.HttpResponse: The HTTP response object containing the generated text by Azure OpenAI.
    """
    # リクエストボディから text の値を取り出す
    req_text = req.get_json().get("text")

    # Azure OpenAI に渡す
    chat_response = chat_completions(req_text)

    # 結果を json 内の text に入れて返す
    return func.HttpResponse(
        json.dumps({"text": chat_response}, ensure_ascii=False),
        mimetype="application/json",
        charset="utf-8"
    )